### ISSUE TITLE
Protobuf error when running hosted.

### ISSUE THREAD

**Issue by LightBreakfast** [aws-samples/aws-iot-securetunneling-web-ssh#4]
Receiving the following error when starting up the web page hosted in S3.

```    ERROR Error: Uncaught (in promise): Error: illegal token '<' (../../../assets/protobuf/format.proto, line 1)
Error: illegal token '<' (../../../assets/protobuf/format.proto, line 1)
    at illegal (parse.js:96:1)
    at parse (parse.js:796:1)
    at process (root.js:127:1)
    at root.js:194:1
    at XMLHttpRequest.fetchOnReadyStateChange [as __zone_symbol__ON_PROPERTYreadystatechange] (index.js:103:1)
    at XMLHttpRequest.wrapFn (zone.js:766:1)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28679:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at rejected (tslib.es6.js:74:89)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.js:28692:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28679:1)
```
    
Then when you try and connect, this error prevents the connection. (Which I'm guessing is related to the above).
    
```    ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'verify')
TypeError: Cannot read properties of undefined (reading 'verify')
    at SocketService.<anonymous> (socket.service.ts:152:41)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (tslib.es6.js:72:1)
    at SocketService.sendB64Message (socket.service.ts:141:33)
    at WebSocket.value (socket.service.ts:43:74)
    at SocketService.startStream (socket.service.ts:168:28)
    at SocketService.openSSH (socket.service.ts:181:10)
    at SocketService.onWebSocketOpen (socket.service.ts:60:10)
    at resolvePromise (zone.js:1211:1)
    at new ZoneAwarePromise (zone.js:1430:1)
    at __awaiter (tslib.es6.js:72:1)
    at SocketService.sendB64Message (socket.service.ts:141:33)
    at WebSocket.value (socket.service.ts:43:74)
    at SocketService.startStream (socket.service.ts:168:28)
    at SocketService.openSSH (socket.service.ts:181:10)
    at SocketService.onWebSocketOpen (socket.service.ts:60:10)
    at socket.onopen [as __zone_symbol__ON_PROPERTYopen] (socket.service.ts:44:40)
    at WebSocket.wrapFn (zone.js:766:1)
```

Strangely enough, if I run it locally (via ng serve), I get neither of these messages and I can connect to through the SSH tunnel successfully...

Any ideas?

![socketerror](https://user-images.githubusercontent.com/49665542/175870545-d0ce0b3c-fcf8-4050-bf6b-bd9ff6b45dba.jpg)
.

**Comment by alifrugal** [comment]
Hi, 

Do you use cloudfront to serve the website hosted on S3, if not you might try: https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serve-static-website/

**Comment by royzhao7** [comment]
Hi the path of proto file should access by url  like 'http://localhost:4200/assests/proto/awesome.proto'
